run_name: "biovid_coral_baseline"

# BioVid Dataset Settings
biovid_settings:
  # features_path: "/home/nbi/marlin/biovid_multimodal_marlin_features/multimodal_marlin_base/"  # multimodal marlin features
  features_path: "/home/nbi/marlin/wan_features/"  # "/home/nbi/marlin/wan_features/" for single modality marlin features
  meta_path: "/home/nbi/marlin/wan_features/meta.json"  # Update this path
  split_ratio: 0.8
  temporal_pooling: "mean"  # Options: mean, max, sample
  flatten: true
  input_format: "CTHW"  # Options: CTHW ([C,T,H,W]) or TCHW ([T,C*H*W])(for multimodal marlin features)
  num_classes_stimulus: 5  # BioVid has 5 pain intensity levels

# Model Architecture Parameters
model_params:
  encoder_hidden_dims: [512, 256]  # MLP layers after feature extraction
  encoder_dropout: 0.5
  use_distance_penalty: true
  focal_gamma: 2.0
  label_smoothing: 0.1

# Optimizer Parameters
optimizer_params:
  optimizer_name: "AdamW"  # Options: Adam, AdamW
  learning_rate: 5.0e-4
  weight_decay: 1.0e-4

# Learning Rate Scheduler
lr_scheduler_params:
  use_scheduler: true
  factor: 0.5
  patience: 5
  min_lr: 1.0e-6

# Training Parameters
trainer_params:
  batch_size: 32
  max_epochs: 500
  early_stop_patience: 150
  model_summary_depth: 2
  monitor_metric: "val_stim_QWK"  # Using stimulus metrics since we're training on BioVid only
  seed: 42 