# Example configuration YAML with additional callback options
# Shows how to configure learning rate scheduler and other callbacks

run_name: "multitask_joint_with_callbacks"

# Model configuration
model:
  input_dim: 768                 # (int) Input dimensionality (feature size)
  num_pain_classes: 5            # (int) Ordinal classes for pain
  num_stimulus_classes: 5        # (int) Ordinal classes for stimulus
  encoder_hidden_dims: [512,256] # (list[int]) Hidden layers for encoder MLP (or [] / null for linear encoder)
  encoder_dropout: 0.5           # (float) Dropout rate in encoder

# Optimizer configuration
optimizer:
  optimizer_name: AdamW          # (str) Optimizer type: 'Adam' or 'AdamW'
  learning_rate: 0.0001          # (float) Initial learning rate
  weight_decay: 0.01             # (float) Weight decay for optimizer

# Loss configuration
loss:
  pain_loss_weight: 1.0          # (float) Relative loss weight for pain task
  stim_loss_weight: 1.0          # (float) Relative loss weight for stim task
  label_smoothing: 0.1           # (float) Label smoothing amount [0,1)
  use_distance_penalty: false    # (bool) Penalize mistakes more for farther off predictions

# Learning rate scheduler configuration
lr_scheduler:
  use_scheduler: true            # (bool) Whether to use the learning rate scheduler
  factor: 0.5                    # (float) Factor by which to reduce learning rate
  patience: 5                    # (int) Number of epochs with no improvement after which to reduce LR
  min_lr: 1.0e-6                 # (float) Minimum learning rate

# Model summary configuration
model_summary_depth: 3           # (int) Depth for model summary display (default: 2)

# Training configuration
batch_size: 64                   # (int) Training batch size
max_epochs: 75                   # (int) Number of training epochs
early_stop_patience: 15          # (int) Patience for early stopping
seed: 42                         # (int) Random seed for reproducibility

# Data paths
syracuse_meta_path: "/path/to/syracuse/meta.json"
syracuse_config_path: "/path/to/syracuse/config.yaml"
biovid_features_path: "/path/to/biovid/features.npz"
biovid_meta_path: "/path/to/biovid/meta.json"

# Cross-validation configuration (when running in cv mode)
cv_fold: 0                       # (int) Default CV fold to use in train/test mode

# Data processing options
temporal_pooling: "mean"         # (str) Temporal pooling method: "mean", "max", or "sample"
flatten: true                    # (bool) Whether to flatten input features
balanced_sampling: false         # (bool) Whether to use balanced sampling
split_ratio: 0.8                 # (float) Train/val split ratio for BioVid

# Usage example:
# python train_multitask.py --config example_config_with_callbacks.yaml --mode cv --monitor_metric val_pain_QWK 